In [28]:
import pandas as pd

In [29]:
import numpy as np

In [32]:
data = pd.Series([.25,.5,.75,1.0],index=['a','b','c','d'])

In [33]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [34]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [35]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [36]:
data.info()

<class 'pandas.core.series.Series'>
Index: 4 entries, a to d
Series name: None
Non-Null Count  Dtype  
--------------  -----  
4 non-null      float64
dtypes: float64(1)
memory usage: 236.0+ bytes


In [37]:
data.shape

(4,)

In [38]:
pd.__version__

'1.4.4'

In [40]:
A = pd.Series([2,3,4,5],index=['q','r','t','u'])

In [41]:
A

q    2
r    3
t    4
u    5
dtype: int64

In [42]:
A.values

array([2, 3, 4, 5])

In [43]:
type(A)

pandas.core.series.Series

In [44]:
type(A.values)

numpy.ndarray

In [52]:
A['t']

4

In [54]:
A['q':'t']

q    2
r    3
t    4
dtype: int64

In [55]:
grades_dict = {'A':4,'A-':3.5,'B':3,'B-':2.5,'C':2}

In [56]:
grades = pd.Series(grades_dict)

In [57]:
grades

A     4.0
A-    3.5
B     3.0
B-    2.5
C     2.0
dtype: float64

In [58]:
grades.values

array([4. , 3.5, 3. , 2.5, 2. ])

In [59]:
grades.index

Index(['A', 'A-', 'B', 'B-', 'C'], dtype='object')

In [60]:
(grades.values)*2

array([8., 7., 6., 5., 4.])

In [61]:
(grades.values)**

SyntaxError: invalid syntax (2353168950.py, line 1)

In [62]:
(grades.values)*(grades.values)

array([16.  , 12.25,  9.  ,  6.25,  4.  ])

In [63]:
grades.values[4=10]

SyntaxError: invalid syntax (3152874681.py, line 1)

In [64]:
grades[0:2]

A     4.0
A-    3.5
dtype: float64

In [65]:
grades['A':'B-']

A     4.0
A-    3.5
B     3.0
B-    2.5
dtype: float64

In [66]:
marks_dict = {'A':85,'A-':80,'B':75,'B-':70,'C':65}
marks = pd.Series(marks_dict)

In [67]:
marks

A     85
A-    80
B     75
B-    70
C     65
dtype: int64

In [68]:
rs = pd.DataFrame({'grades':grades,'marks':marks})

In [69]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [71]:
A[0].ndim

0

In [72]:
A[2].ndim

0

In [73]:
A.ndim

1

In [74]:
rs.ndim

2

In [75]:
rs[0,0]

KeyError: (0, 0)

In [76]:
RS.TP

NameError: name 'RS' is not defined

In [77]:
RS.T

NameError: name 'RS' is not defined

In [78]:
rs.T

A    A-     B    B-     C
grades   4.0   3.5   3.0   2.5   2.0
marks   85.0  80.0  75.0  70.0  65.0

In [79]:
rs.T

A    A-     B    B-     C
grades   4.0   3.5   3.0   2.5   2.0
marks   85.0  80.0  75.0  70.0  65.0

In [80]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [81]:
rs.values

array([[ 4. , 85. ],
       [ 3.5, 80. ],
       [ 3. , 75. ],
       [ 2.5, 70. ],
       [ 2. , 65. ]])

In [82]:
rs.values[2,1]

75.0

In [83]:
rs.values[0,0]

4.0

In [84]:
rs.columns

Index(['grades', 'marks'], dtype='object')

In [85]:
rs.columns[0]

'grades'

In [89]:
rs['ScaledMarks'] = rs['marks']/90

In [90]:
rs

grades  marks  ScaledMarks
A      4.0     85     0.944444
A-     3.5     80     0.888889
B      3.0     75     0.833333
B-     2.5     70     0.777778
C      2.0     65     0.722222

In [128]:
rs.ndim

2

In [93]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [114]:
greater = rs[rs['marks']>70]

In [115]:
greater

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75

In [116]:
rs

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75
B-     2.5     70
C      2.0     65

In [117]:
greater

grades  marks
A      4.0     85
A-     3.5     80
B      3.0     75

In [119]:
greater.values[1,0]

3.5

In [126]:
greater.values.transpose()

array([[ 4. ,  3.5,  3. ],
       [85. , 80. , 75. ]])

In [127]:
rs.ndim

2

In [133]:
Nan = pd.DataFrame([{'a':1,'b':2,'c':3},{'a':4,'c':6}])

In [143]:
Nan.dropna()

a     b  c
0  1   2.0  3
1  4  none  6

In [144]:
Nan = Nan.fillna('none')

In [145]:
Nan

a     b  c
0  1   2.0  3
1  4  none  6

In [146]:
Nan.dropna

<bound method DataFrame.dropna of    a     b  c
0  1   2.0  3
1  4  none  6>

In [147]:
Nan.dropna()

a     b  c
0  1   2.0  3
1  4  none  6

In [148]:
Nan

a     b  c
0  1   2.0  3
1  4  none  6

In [163]:
Nan.c[0:1]

0    3
Name: c, dtype: int64

In [164]:
Nan.values

array([[1, 2.0, 3],
       [4, 'none', 6]], dtype=object)

In [167]:
Nan.iloc[1,1]

'none'

In [168]:
Nan.iloc[1,2]

6

In [172]:
Nan[0:1]

a    b  c
0  1  2.0  3

In [173]:
Nan[1:2]

a     b  c
1  4  none  6

In [181]:
Nan.iloc[0,2]

3

In [182]:
Nan.loc[1,:]

a       4
b    none
c       6
Name: 1, dtype: object

In [183]:
Nan.loc[:,1]

KeyError: 1

In [184]:
Nan.iloc[::-1,:]

a     b  c
1  4  none  6
0  1   2.0  3

In [186]:
covid = pd.read_csv('/users/brycefranzen/public/data/country_wise_latest.csv')

In [187]:
covid

Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0           Afghanistan      36263    1269      25198    9796        106   
1               Albania       4880     144       2745    1991        117   
2               Algeria      27973    1163      18837    7973        616   
3               Andorra        907      52        803      52         10   
4                Angola        950      41        242     667         18   
..                  ...        ...     ...        ...     ...        ...   
182  West Bank and Gaza      10621      78       3752    6791        152   
183      Western Sahara         10       1          8       1          0   
184               Yemen       1691     483        833     375         10   
185              Zambia       4552     140       2815    1597         71   
186            Zimbabwe       2704      36        542    2126        192   

     New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0            10             18                3.50                  69.49   
1             6             63                2.95                  56.25   
2             8            749                4.16                  67.34   
3             0              0                5.73                  88.53   
4             1              0                4.32                  25.47   
..          ...            ...                 ...                    ...   
182           2              0                0.73                  35.33   
183           0              0               10.00                  80.00   
184           4             36               28.56                  49.26   
185           1            465                3.08                  61.84   
186           2             24                1.33                  20.04   

     Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                      5.04                35526            737   
1                      5.25                 4171            709   
2                      6.17                23691           4282   
3                      6.48                  884             23   
4                     16.94                  749            201   
..                      ...                  ...            ...   
182                    2.08                 8916           1705   
183                   12.50                   10              0   
184                   57.98                 1619             72   
185                    4.97                 3326           1226   
186                    6.64                 1713            991   

     1 week % increase             WHO Region  
0                 2.07  Eastern Mediterranean  
1                17.00                 Europe  
2                18.07                 Africa  
3                 2.60                 Europe  
4                26.84                 Africa  
..                 ...                    ...  
182              19.12  Eastern Mediterranean  
183               0.00                 Africa  
184               4.45  Eastern Mediterranean  
185              36.86                 Africa  
186              57.85                 Africa  

[187 rows x 15 columns]

In [188]:
covid.values

array([['Afghanistan', 36263, 1269, ..., 737, 2.07,
        'Eastern Mediterranean'],
       ['Albania', 4880, 144, ..., 709, 17.0, 'Europe'],
       ['Algeria', 27973, 1163, ..., 4282, 18.07, 'Africa'],
       ...,
       ['Yemen', 1691, 483, ..., 72, 4.45, 'Eastern Mediterranean'],
       ['Zambia', 4552, 140, ..., 1226, 36.86, 'Africa'],
       ['Zimbabwe', 2704, 36, ..., 991, 57.85, 'Africa']], dtype=object)

In [189]:
covid.columns

Index(['Country/Region', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'New cases', 'New deaths', 'New recovered', 'Deaths / 100 Cases',
       'Recovered / 100 Cases', 'Deaths / 100 Recovered',
       'Confirmed last week', '1 week change', '1 week % increase',
       'WHO Region'],
      dtype='object')

In [190]:
covid.head(10)

Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0          Afghanistan      36263    1269      25198    9796        106   
1              Albania       4880     144       2745    1991        117   
2              Algeria      27973    1163      18837    7973        616   
3              Andorra        907      52        803      52         10   
4               Angola        950      41        242     667         18   
5  Antigua and Barbuda         86       3         65      18          4   
6            Argentina     167416    3059      72575   91782       4890   
7              Armenia      37390     711      26665   10014         73   
8            Australia      15303     167       9311    5825        368   
9              Austria      20558     713      18246    1599         86   

   New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0          10             18                3.50                  69.49   
1           6             63                2.95                  56.25   
2           8            749                4.16                  67.34   
3           0              0                5.73                  88.53   
4           1              0                4.32                  25.47   
5           0              5                3.49                  75.58   
6         120           2057                1.83                  43.35   
7           6            187                1.90                  71.32   
8           6            137                1.09                  60.84   
9           1             37                3.47                  88.75   

   Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                    5.04                35526            737   
1                    5.25                 4171            709   
2                    6.17                23691           4282   
3                    6.48                  884             23   
4                   16.94                  749            201   
5                    4.62                   76             10   
6                    4.21               130774          36642   
7                    2.67                34981           2409   
8                    1.79                12428           2875   
9                    3.91                19743            815   

   1 week % increase             WHO Region  
0               2.07  Eastern Mediterranean  
1              17.00                 Europe  
2              18.07                 Africa  
3               2.60                 Europe  
4              26.84                 Africa  
5              13.16               Americas  
6              28.02               Americas  
7               6.89                 Europe  
8              23.13        Western Pacific  
9               4.13                 Europe

In [203]:
covid.drop(['WHO Region'],axis=1,inplace=True)

In [204]:
covid

Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
0        36263    1269      25198    9796        106          10   
1         4880     144       2745    1991        117           6   
2        27973    1163      18837    7973        616           8   
3          907      52        803      52         10           0   
4          950      41        242     667         18           1   
..         ...     ...        ...     ...        ...         ...   
182      10621      78       3752    6791        152           2   
183         10       1          8       1          0           0   
184       1691     483        833     375         10           4   
185       4552     140       2815    1597         71           1   
186       2704      36        542    2126        192           2   

     New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0               18                3.50                  69.49   
1               63                2.95                  56.25   
2              749                4.16                  67.34   
3                0                5.73                  88.53   
4                0                4.32                  25.47   
..             ...                 ...                    ...   
182              0                0.73                  35.33   
183              0               10.00                  80.00   
184             36               28.56                  49.26   
185            465                3.08                  61.84   
186             24                1.33                  20.04   

     Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                      5.04                35526            737   
1                      5.25                 4171            709   
2                      6.17                23691           4282   
3                      6.48                  884             23   
4                     16.94                  749            201   
..                      ...                  ...            ...   
182                    2.08                 8916           1705   
183                   12.50                   10              0   
184                   57.98                 1619             72   
185                    4.97                 3326           1226   
186                    6.64                 1713            991   

     1 week % increase  
0                 2.07  
1                17.00  
2                18.07  
3                 2.60  
4                26.84  
..                 ...  
182              19.12  
183               0.00  
184               4.45  
185              36.86  
186              57.85  

[187 rows x 13 columns]

In [205]:
covid.head(10)

Confirmed  Deaths  Recovered  Active  New cases  New deaths  New recovered  \
0      36263    1269      25198    9796        106          10             18   
1       4880     144       2745    1991        117           6             63   
2      27973    1163      18837    7973        616           8            749   
3        907      52        803      52         10           0              0   
4        950      41        242     667         18           1              0   
5         86       3         65      18          4           0              5   
6     167416    3059      72575   91782       4890         120           2057   
7      37390     711      26665   10014         73           6            187   
8      15303     167       9311    5825        368           6            137   
9      20558     713      18246    1599         86           1             37   

   Deaths / 100 Cases  Recovered / 100 Cases  Deaths / 100 Recovered  \
0                3.50                  69.49                    5.04   
1                2.95                  56.25                    5.25   
2                4.16                  67.34                    6.17   
3                5.73                  88.53                    6.48   
4                4.32                  25.47                   16.94   
5                3.49                  75.58                    4.62   
6                1.83                  43.35                    4.21   
7                1.90                  71.32                    2.67   
8                1.09                  60.84                    1.79   
9                3.47                  88.75                    3.91   

   Confirmed last week  1 week change  1 week % increase  
0                35526            737               2.07  
1                 4171            709              17.00  
2                23691           4282              18.07  
3                  884             23               2.60  
4                  749            201              26.84  
5                   76             10              13.16  
6               130774          36642              28.02  
7                34981           2409               6.89  
8                12428           2875              23.13  
9                19743            815               4.13

In [209]:
covid.rename(columns={'Recovered':'Animals'})

Confirmed  Deaths  Animals  Active  New cases  New deaths  New recovered  \
0        36263    1269    25198    9796        106          10             18   
1         4880     144     2745    1991        117           6             63   
2        27973    1163    18837    7973        616           8            749   
3          907      52      803      52         10           0              0   
4          950      41      242     667         18           1              0   
..         ...     ...      ...     ...        ...         ...            ...   
182      10621      78     3752    6791        152           2              0   
183         10       1        8       1          0           0              0   
184       1691     483      833     375         10           4             36   
185       4552     140     2815    1597         71           1            465   
186       2704      36      542    2126        192           2             24   

     Deaths / 100 Cases  Recovered / 100 Cases  Deaths / 100 Recovered  \
0                  3.50                  69.49                    5.04   
1                  2.95                  56.25                    5.25   
2                  4.16                  67.34                    6.17   
3                  5.73                  88.53                    6.48   
4                  4.32                  25.47                   16.94   
..                  ...                    ...                     ...   
182                0.73                  35.33                    2.08   
183               10.00                  80.00                   12.50   
184               28.56                  49.26                   57.98   
185                3.08                  61.84                    4.97   
186                1.33                  20.04                    6.64   

     Confirmed last week  1 week change  1 week % increase  
0                  35526            737               2.07  
1                   4171            709              17.00  
2                  23691           4282              18.07  
3                    884             23               2.60  
4                    749            201              26.84  
..                   ...            ...                ...  
182                 8916           1705              19.12  
183                   10              0               0.00  
184                 1619             72               4.45  
185                 3326           1226              36.86  
186                 1713            991              57.85  

[187 rows x 13 columns]

In [210]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Confirmed               187 non-null    int64  
 1   Deaths                  187 non-null    int64  
 2   Recovered               187 non-null    int64  
 3   Active                  187 non-null    int64  
 4   New cases               187 non-null    int64  
 5   New deaths              187 non-null    int64  
 6   New recovered           187 non-null    int64  
 7   Deaths / 100 Cases      187 non-null    float64
 8   Recovered / 100 Cases   187 non-null    float64
 9   Deaths / 100 Recovered  187 non-null    float64
 10  Confirmed last week     187 non-null    int64  
 11  1 week change           187 non-null    int64  
 12  1 week % increase       187 non-null    float64
dtypes: float64(4), int64(9)
memory usage: 19.1 KB


In [219]:
covid.replace(0,'none')

Confirmed Deaths Recovered Active New cases New deaths New recovered  \
none      36263   1269     25198   9796       106         10            18   
1          4880    144      2745   1991       117          6            63   
2         27973   1163     18837   7973       616          8           749   
3           907     52       803     52        10       none          none   
4           950     41       242    667        18          1          none   
...         ...    ...       ...    ...       ...        ...           ...   
182       10621     78      3752   6791       152          2          none   
183          10      1         8      1      none       none          none   
184        1691    483       833    375        10          4            36   
185        4552    140      2815   1597        71          1           465   
186        2704     36       542   2126       192          2            24   

     Deaths / 100 Cases Recovered / 100 Cases Deaths / 100 Recovered  \
none                3.5                 69.49                   5.04   
1                  2.95                 56.25                   5.25   
2                  4.16                 67.34                   6.17   
3                  5.73                 88.53                   6.48   
4                  4.32                 25.47                  16.94   
...                 ...                   ...                    ...   
182                0.73                 35.33                   2.08   
183                10.0                  80.0                   12.5   
184               28.56                 49.26                  57.98   
185                3.08                 61.84                   4.97   
186                1.33                 20.04                   6.64   

      Confirmed last week 1 week change 1 week % increase  
none                35526           737              2.07  
1                    4171           709              17.0  
2                   23691          4282             18.07  
3                     884            23               2.6  
4                     749           201             26.84  
...                   ...           ...               ...  
182                  8916          1705             19.12  
183                    10          none              none  
184                  1619            72              4.45  
185                  3326          1226             36.86  
186                  1713           991             57.85  

[187 rows x 13 columns]

In [220]:
covid

Confirmed Deaths Recovered Active New cases New deaths New recovered  \
none      36263   1269     25198   9796       106         10            18   
1          4880    144      2745   1991       117          6            63   
2         27973   1163     18837   7973       616          8           749   
3           907     52       803     52        10       none          none   
4           950     41       242    667        18          1          none   
...         ...    ...       ...    ...       ...        ...           ...   
182       10621     78      3752   6791       152          2          none   
183          10      1         8      1      none       none          none   
184        1691    483       833    375        10          4            36   
185        4552    140      2815   1597        71          1           465   
186        2704     36       542   2126       192          2            24   

     Deaths / 100 Cases Recovered / 100 Cases Deaths / 100 Recovered  \
none                3.5                 69.49                   5.04   
1                  2.95                 56.25                   5.25   
2                  4.16                 67.34                   6.17   
3                  5.73                 88.53                   6.48   
4                  4.32                 25.47                  16.94   
...                 ...                   ...                    ...   
182                0.73                 35.33                   2.08   
183                10.0                  80.0                   12.5   
184               28.56                 49.26                  57.98   
185                3.08                 61.84                   4.97   
186                1.33                 20.04                   6.64   

      Confirmed last week 1 week change 1 week % increase  
none                35526           737              2.07  
1                    4171           709              17.0  
2                   23691          4282             18.07  
3                     884            23               2.6  
4                     749           201             26.84  
...                   ...           ...               ...  
182                  8916          1705             19.12  
183                    10          none              none  
184                  1619            72              4.45  
185                  3326          1226             36.86  
186                  1713           991             57.85  

[187 rows x 13 columns]

In [221]:
covid

Confirmed Deaths Recovered Active New cases New deaths New recovered  \
none      36263   1269     25198   9796       106         10            18   
1          4880    144      2745   1991       117          6            63   
2         27973   1163     18837   7973       616          8           749   
3           907     52       803     52        10       none          none   
4           950     41       242    667        18          1          none   
...         ...    ...       ...    ...       ...        ...           ...   
182       10621     78      3752   6791       152          2          none   
183          10      1         8      1      none       none          none   
184        1691    483       833    375        10          4            36   
185        4552    140      2815   1597        71          1           465   
186        2704     36       542   2126       192          2            24   

     Deaths / 100 Cases Recovered / 100 Cases Deaths / 100 Recovered  \
none                3.5                 69.49                   5.04   
1                  2.95                 56.25                   5.25   
2                  4.16                 67.34                   6.17   
3                  5.73                 88.53                   6.48   
4                  4.32                 25.47                  16.94   
...                 ...                   ...                    ...   
182                0.73                 35.33                   2.08   
183                10.0                  80.0                   12.5   
184               28.56                 49.26                  57.98   
185                3.08                 61.84                   4.97   
186                1.33                 20.04                   6.64   

      Confirmed last week 1 week change 1 week % increase  
none                35526           737              2.07  
1                    4171           709              17.0  
2                   23691          4282             18.07  
3                     884            23               2.6  
4                     749           201             26.84  
...                   ...           ...               ...  
182                  8916          1705             19.12  
183                    10          none              none  
184                  1619            72              4.45  
185                  3326          1226             36.86  
186                  1713           991             57.85  

[187 rows x 13 columns]